name: flutter_clean_architecture_riverpod
description: A new Flutter base template using Riverpod and Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.0
  retrofit: 4.4.1
  dio_http_formatter: ^3.0.0

  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.0.0

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.20.2
  connectivity_plus: ^6.0.0
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  
  # UI
  smooth_page_indicator: ^1.1.0 # Added for onboarding dots

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.3
  retrofit_generator: 9.1.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
  generate: true # Added for localization generation
  assets:
    - assets/images/
    - assets/translations/